# Generated by Django 2.1.7 on 2019-03-04 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='类名')),
            ],
            options={
                'verbose_name_plural': '002. 课程分类',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='课程名')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, '入门'), (1, '中级'), (2, '高级')], default=1, help_text='默认中级', verbose_name='难度等级')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Category', verbose_name='所属课程类')),
            ],
            options={
                'verbose_name_plural': '003. 专题课',
            },
        ),
        migrations.CreateModel(
            name='DegreeCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='学位课')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, '入门'), (1, '中级'), (2, '高级')], default=1, help_text='默认中级', verbose_name='难度等级')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Category', verbose_name='所属课程类')),
            ],
            options={
                'verbose_name_plural': '004. 学位课',
            },
        ),
        migrations.CreateModel(
            name='PricePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('during', models.PositiveIntegerField(choices=[(1, '一天'), (7, '一周'), (14, '两周'), (30, '一个月'), (180, '半年'), (365, '一年'), (730, '两年')], verbose_name='学习周期')),
                ('price', models.DecimalField(decimal_places=2, help_text='精确到小数点后两位', max_digits=8, verbose_name='价格')),
                ('object_id', models.IntegerField(verbose_name='generic_fk_course')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='表ID')),
            ],
            options={
                'verbose_name_plural': '005. 课程价格策略表',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='老师名')),
                ('age', models.PositiveSmallIntegerField(verbose_name='年龄')),
            ],
            options={
                'verbose_name_plural': '001. 老师表',
            },
        ),
        migrations.AddField(
            model_name='degreecourses',
            name='teacher',
            field=models.ManyToManyField(to='app01.Teachers', verbose_name='任课老师s'),
        ),
        migrations.AddField(
            model_name='courses',
            name='teacher',
            field=models.ManyToManyField(to='app01.Teachers', verbose_name='任课老师s'),
        ),
        migrations.AlterUniqueTogether(
            name='pricepolicy',
            unique_together={('object_id', 'content_type', 'price')},
        ),
    ]
